# Sample .travis.yml for R projects.
# Checking a package in a subdirectory: see http://www.rochester.edu/college/gradstudents/jolmsted/blog/2014/01/05/r-pkgs-on-travis/
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
# https://github.com/craigcitro/r-travis/wiki
language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap
install:
- cd ./package
- ../travis-tool.sh install_deps
script: ../travis-tool.sh run_tests
after_failure:
- ../travis-tool.sh dump_logs
notifications:
email:
on_success: change
on_failure: change
